In [27]:
import numpy as np

# Converting a list to Array

In [30]:
lst = [1,2,3,4]
print(type(lst))
arr = np.array(lst)
print(type(arr))
arr = np.array(lst,ndmin = 2)
print(arr)

<class 'list'>
<class 'numpy.ndarray'>
[[1 2 3 4]]


# 2. Arrange function
    The arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval. The interval   mentioned is half-opened i.e. [Start, Stop)

np.arange(1,10,2)

In [36]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9


# 3. Multidimensional Array

In [46]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(type(arr))
arr

<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 4. Size Function
In Python, numpy.size() function count the number of elements along a given axis (0 - Rows | 1 - Columns)

In [50]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])

print('Total : ', arr.size)
print('Rows  : ', np.size(arr,0))
print('Cols  : ', np.size(arr,1))

arr

Total :  12
Rows  :  4
Cols  :  3


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])